### ISSUE TITLE
Simplify yaml format

### ISSUE THREAD

**Issue by sheax0r** [sheax0r/yello#12]
Currently we are using this (note the extra indentation on "checklists"):

``` yaml
List:
  cards:
  - Card:
      checklists:
      - Checklist
        - 1
        - 2
```

Switch to this:

``` yaml
List:
  cards:
  - Card:
    checklists:
    - Checklist
      - 1
      - 2
```

This actually results in slightly different yaml -  the original version produces `{'Card'=>{'checklists'=>[1,2]}}`, but the new version produces `{'Card'=>nil,'checklists'=>[1,2]}`, which is a bit weird but still results in a more readable file.
