### ISSUE TITLE
Shorthand for a single checklist

### ISSUE THREAD

**Issue by drewfradette** [sheax0r/yello#17]
``` yml
Examples:
  cards:
    - Example Card
      desc: Hello world!
      checklist:
        - Item 1
        - Item 2
```

Resulting in a single checklist called "Checklist".
