### ISSUE TITLE
Parse YAML files

### ISSUE THREAD

**Issue by sheax0r** [sheax0r/yello#4]
``` yaml
Not Started:
  cards:
  - Get an email account
  - Have lunch with your managers
  - Get a key card
  - Attend the noob-101 workshop
  - Submit your first bugfix:
      checklists:
      - Process:
        - Write tests
        - Write code
        - Get it reviewed
        - Merge it
In Progress: {} 
Completed: {} 
```
