### ISSUE TITLE
Support checklists in card definitions

### ISSUE THREAD

**Issue by sheax0r** [sheax0r/yello#7]
``` yaml
Not Started:
  cards:
  - Get an email account
  - Have lunch with your manager
  - Get a key card
  - Attend the noob-101 workshop
  - Submit your first bugfix:
      checklists:
      - Process:
        - Write tests
        - Write code
        - Get it reviewed
        - Merge it
In Progress: {} 
Completed: {} 
```
